# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [

    ]
