# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170719_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=512),
        ),
    ]
